// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tkqwuqvrpuwpbdjootoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrcXd1cXZycHV3cGJkam9vdG9jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5ODM3NTQsImV4cCI6MjA2NjU1OTc1NH0.91w_RvJW1Q5h48IAcDsb7cnKLrLq_S96bcEVUcA6Gx0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);